## calculate storm, interstorm durations and storm depth from 
## data generated by Landlab Precipitation Distribution

## read in the data and put into a single dataframe
simsNum <- read.csv("SimsNum.txt", header=FALSE)
duration <- read.csv("StormEventDuration.txt", header=FALSE)
rainfall <- read.csv("StormEventRainRate.txt", header=FALSE)

dat <- cbind(simsNum,duration, rainfall)
colnames(dat) <- c("year", "duration", "rainRate")
num_records <- length(dat$year)

## CREATE STORM and INTERSTORM DATAFRAMEs 
stormEvents <- data.frame("year"=integer(), "duration"=double(), "rainRate"=double(), stringsAsFactors = FALSE)
interstormEvents <- data.frame("year"=integer(), "duration"=double(), "rainRate"=double(), stringsAsFactors = FALSE)

## populate storm and interstorm dataframes
for (i in 1:num_records){
  if(dat$rainRate[i] == 0){
    interstormEvents <- rbind(interstormEvents, data.frame("year"=dat$year[i],"duration"=dat$duration[i], 
                                                           "rainRate"=dat$rainRate[i]))
  }else{
    stormEvents <- rbind(stormEvents, data.frame("year"=dat$year[i], "duration"=dat$duration[i], 
                                                 "rainRate"=dat$rainRate[i]))
  }
}

## calculate mean durations and depth
mean_storm_duration <- mean(stormEvents$duration)
mean_interstorm_duration <- mean(interstormEvents$duration)
mean_storm_depth <- mean(stormEvents$rainRate)

## Look at yearly/simly precipitation totals
yearlyPrecip <- ddply(stormEvents,~year,summarise, sum=sum(rainRate))
barplot(yearlyPrecip$sum, main="Total Annual Rainfall Generated",
        xlab="Year")
abline(h=mean(yearlyPrecip$sum), col="blue")
print(mean(yearlyPrecip$sum))

yearlyRainfall <- read.csv("TotalAnnualRainfall-1337.txt", header=FALSE)
barplot(yearlyRainfall$V1, main="Total Annual Rainfall Generated",
        xlab="Year")
  