## PLOT ANNUAL PRECIPITATION GENERATED BY LANDLAB PRECIPITATION DISTRIBUTION

## read in file
dat <- read.csv("TotalAnnualRainfall-1337.txt", header=FALSE)

## generate plot
barplot(dat$V1, main="Landlab Generated Annual Precipitation (m) from seed 1337", xlab="Sim")

## add line for mean average precipitation from climate data
abline(h=0.902, col="red")
text(35.5, .952, "MAP", col="red")

## add line for mean average precipitation from generated data
abline(h=mean(dat$V1), col="blue")
text(35.5, mean(dat$V1)+0.05, "mean", col="blue")

## add line for median average precipitation from generated data
abline(h=median(dat$V1), col="green")
text(35.5, median(dat$V1)-0.05, "median", col="green")
