## PLOT ANNUAL PRECIPITATION GENERATED BY LANDLAB PRECIPITATION DISTRIBUTION

## read in file
dat <- read.csv("TotalAnnualRainfall-thr-3hr-3779.txt", header=FALSE)

## calculate mean and median
meanTotAnnPrecip <- mean(dat$V1)
medianTotAnnPrecip <- median(dat$V1)

## Mean Annual Precipitation from climate data
map <- 0.902

## generate plot
barplot(dat$V1, main="Generated Rainfall from 0.25mm Threshold, \n 6-hr individual storm Parameters", xlab="Sim")

## add line for mean average precipitation from climate data
abline(h = map, col="red")
text(35.5, .952, "MAP", col="red")

## add line for mean average precipitation from generated data
abline(h = meanTotAnnPrecip, col="blue")
text(35.5, meanTotAnnPrecip + 0.05, "mean", col="blue")

## add line for median average precipitation from generated data
abline(h = medianTotAnnPrecip, col="green")
text(35.5, medianTotAnnPrecip - 0.05, "median", col="green")

# Add mean total annual precipitation to plot
text(30, 2, paste("Mean =", round(meanTotAnnPrecip, 4), "\n Median =", 
                            round(medianTotAnnPrecip, 4), "\n Climate MAP =",
                            map))
